# Generated by Django 2.0 on 2018-01-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_comment_belong_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='under_comments', to='firstapp.Aritcle'),
        ),
    ]
